### PR TITLE
Create Sri Lankan Tech Community

### PR DESCRIPTION
**Pull request by ViknarajM**

### CODE REVIEW

**Comment by ViknarajM** [comment]
No conflicts

**Comment by tiagocostapt** [comment]
Hi @ViknarajM , you need to add some files to the PR so that I can approve the PR. Check this Pull Request to know more - 
https://github.com/globalazure/communities/pull/315

If you have some questions about it, just let me know, and I our someone else from the Global Azure team will help you.
Happy to have you community at Global Azure 2024.

**Comment by ViknarajM** [comment]
Hi, please provide the steps to create the Pull Request.

**Comment by ViknarajM** [comment]
I'm going to create a new request

**Pull request closed without merging**
