### PR TITLE
Added agenda to Global Azure Stockholm

### PR DESCRIPTION
**Pull request by StefanIvemo**
Added agenda to Global Azure Stockholm

### CODE REVIEW

**Comment by noopman** [comment]
I love this effort. @davidjrh has some input on that! <3

**Comment by davidjrh** [comment]
Yeah, @StefanIvemo I saw you are injecting the  Sessionize script into the community page, and that gave us a better idea, that is to automatically create a link to the Schedule filtered by community (and viceversa, each community session will have a link back to the community page). With that change, we'll avoid to have duplicate schedules and have a better UX on the site. 

If that sounds good to you, we'll do that change and also remove that script part from the PR.

**Comment by StefanIvemo** [comment]
@davidjrh ok, cool! Will remove the Sessionize script.

**Comment by noopman** [comment]
Well done though @StefanIvemo, all we need to do is reject the PR and generalise your approach for the benefit of all! Community at work! <3

**Comment by StefanIvemo** [comment]
Don't reject it 😱😊. Made some other minor changes as well to the community page. Pushed a new commit without the Sessionize script.

**Comment by davidjrh** [comment]
@StefanIvemo we've implemented the button redirecting to the schedule page filtered by community. Each community session now also links back to the community page when clicking on the "View community info" link. 

image

image

**Comment by StefanIvemo** [comment]
@davidjrh That's awesome! Looks great. ❤️

**Pull request merged**
