### PR TITLE
adding Azure Quebec Community info

### PR DESCRIPTION
**Pull request by BelRarr**
Thank you! :)

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hello @BelRarr , please add a basic index.md file for your community! It really does not need to have a lot of information, but it equates to a page on your shared Global Azure site that you can use as a jump-off point linking back to your community!

**Comment by BelRarr** [comment]
@noopman I just added the index.md file as requested. Sorry for the delay! :)

**Comment by noopman** [comment]
Welcome with a pin on the Global Azure communities map! <3

**Comment by BelRarr** [comment]
@noopman thank you so much! :)  yay!

**Pull request merged**
