### PR TITLE
Global Azure Bootcamp Dublin Ireland 

### PR DESCRIPTION
**Pull request by followtushar**

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hello @followtushar - thanks for the submission. I need to ask you to include an index.md file in the same directory in your pull request, please! For inspiration on content, please review the other folders next to yours!

**Comment by noopman** [comment]
*PING* @followtushar - I am hoping to add you to the map ASAP, just need this one thing resolved, please!

**Comment by followtushar** [comment]
@noopman  Hi Mangus, Apologies for delay! Now the Index.md is added.

**Comment by noopman** [comment]
Perfection, Thank you! Enjoy the pin on the map, and welcome to Global Azure!

**Pull request merged**
