### PR TITLE
AzugDK

### PR DESCRIPTION
**Pull request by marilag**
Happy to participate!

### CODE REVIEW

**Review by tiagocostapt — DISMISSED** [review]
Looks ok. Welcome to Global Azure!

**Comment by hugobarona** [comment]
Hi @marilag . Welcome to the Global Azure. Just a quick question. On the Sessionize Description, you have the URL for the list of sessions. I am getting a 404 not found when trying to access the URL (https://sessionize.com/api/v2/11109/view/Sessions). Can you please double-check if your sessionize event id is correct?

Thanks

**Comment by noopman** [comment]
I have seen this issue before, @tiagocostapt, and you are right. This ID entered is the Sessionize event id. There is one additional ID and that is the API key for the event. @marilag typically those IDs look like this w84xg5cq and they are found in the API/Embed section of your Sessionize event. Get that ID for us and enter it in your data.json! Make sure the API is configured correctly! Thanks!

**Comment by marilag** [comment]
Hello all! Thanks for pointing out. I have fixed it now both for AzugDK and AzugMnl :)

**Pull request merged**
