### PR TITLE
Add Japan Azure User Group (jazug) event.

### PR DESCRIPTION
**Pull request by a-yui**

### CODE REVIEW

**Comment by tiagocostapt** [comment]
@a-yui any update on my comment?

**Comment by a-yui** [comment]
No updates.

**Comment by a-yui** [comment]
@tiagocostapt I cannot see your comment. Is there a problem?

**Review by tiagocostapt — APPROVED** [review]

**Comment by tiagocostapt** [comment]
You're GitHub handle was missing on the json file. I just added it.

**Comment by a-yui** [comment]
@tiagocostapt Thanks for the correction.

**Pull request merged**
