### PR TITLE
changes for styava community

### PR DESCRIPTION
**Pull request by kulkarnikushal17**

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hello there @kulkarnikushal17 ! The Global Azure web site is NOT a billboard. It does not look to me like you are running a Global Azure community event, but rather just listing that you exist. Please advice on what is going on here!

**Review by noopman — CHANGES_REQUESTED** [review]
Hello there @kulkarnikushal17 ! The Global Azure web site is NOT a billboard. It does not look to me like you are running a Global Azure community event, but rather just listing that you exist. Please advice on what is going on here!

**Comment by noopman** [comment]
@tiagocostapt is this a Global Azure event or what is this?

**Comment by tiagocostapt** [comment]
I wanted to comment and pressed the wrong button... 
Just reverted it.

**Comment by tiagocostapt** [comment]
@kulkarnikushal17  are you organizing a Global Azure event?

**Pull request merged**
