### PR TITLE
Microsoft Learn Community GBU

### PR DESCRIPTION
**Pull request by srronaksingh**
all the .DS_Store files now been deleted.

### CODE REVIEW

**Comment by tiagocostapt** [comment]
Hi @srronaksingh, can you please remove these DS_Store files? There are 3 of them.

**Review by srronaksingh — COMMENTED** [review]
all .DS_Store files are removed.

**Comment by srronaksingh** [comment]
> Hi @srronaksingh, can you please remove these DS_Store files? There are 3 of them.

all files of .DS_Store now have been deleted sir, I request you to review the pull request.

**Comment by tiagocostapt** [comment]
This PR is trying to delete the root .gitignore file. We can't approve it. You will need to remove that operation from this PR so I can approve it.

**Comment by srronaksingh** [comment]
> This PR is trying to delete the root .gitignore file. We can't approve it. You will need to remove that operation from this PR so I can approve it.

the process is reverted for .gitignore.

**Comment by srronaksingh** [comment]
The delete process for .gitignore file has now been reverted.

**Comment by srronaksingh** [comment]
I hope now everything works fine.

**Comment by srronaksingh** [comment]
any updates sir ?

**Comment by hugobarona** [comment]
Hi @srronaksingh . Can you please revert the changes to the .gitignore file? The files modified tab should show only 3 files modified, instead of four.

image


Thanks.

**Pull request closed without merging**
