### PR TITLE
Azure Meetup Torino

### PR DESCRIPTION
**Pull request by alberto-annunziata90**
Adding files for Azure Meetup Torino

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hello there @alberto-annunziata90. I am missing the index.dm file in this PR! Would you please add one and update the PR!

**Comment by noopman** [comment]
How is it going @alberto-annunziata90 ?

**Comment by alberto-annunziata90** [comment]
I've done it. Thanks

**Comment by alberto-annunziata90** [comment]
> How is it going @alberto-annunziata90 ?

I add it. Let me know. Thank you for support.

> Hello there @alberto-annunziata90. I am missing the index.dm file in this PR! Would you please add one and update the PR!

I've done it.

**Comment by davidjrh** [comment]
Looks good to me! Merging!

**Pull request merged**
