### PR TITLE
AzureMozambique Folder

### PR DESCRIPTION
**Pull request by appollinno**

### CODE REVIEW

**Comment by tiagocostapt** [comment]
Hi @appollinno I would also need to have a data.json and index.md file to approve this PR. Can you add then? 
You can see some sample files at https://github.com/globalazure/communities/tree/main/2024/azugpt

**Comment by appollinno** [comment]
AZUGMZ
[data.json](https://github.com/globalazure/communities/files/15023068/data.json)
[index.md](https://github.com/globalazure/communities/files/15023069/index.md)

**Comment by appollinno** [comment]
@tiagocostapt,

Im bit lost on this process. I really need your help on this. Find the attached files (data.json, index.md)

**Comment by tiagocostapt** [comment]
Added the files manually. Event is added. Will close this PR.

**Pull request closed without merging**
