### PR TITLE
GlobalAzureMauritius 

### PR DESCRIPTION
**Pull request by isubratty**
-- add folder

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
OH and one more thing! Let's stick to folders without whitespace in the name. Not sure if that would mess up our site!

**Comment by Ouweshs28** [comment]
changes made, please review

**Review by Ouweshs28 — APPROVED** [review]

**Review by noopman — APPROVED** [review]
Great entry - special warm welcome to Student Ambassadors to Global Azure! :D

**Comment by isubratty** [comment]
Thank you Magnus !

Kind Regards,
Muhammad Irfaan Ali Subratty, MIET, MACM,
Young Professional Lead
IET CC-EMEA,
Chairperson
CyberCity ACM Chapter,
Committee Member
IET Mauritius,
Lead
IET Mauritius Young Professional Section,
IET Young Professional Ambassador,
Microsoft Learn Student Ambassador
________________________________

**Comment by noopman** [comment]
Hey there! I checked the [pin map of communities](https://globalazure.net/communities/2022) and note that your loction is pinned to somewhere in Oman - Middle east. I concluded that your Latitude in the data.json file must be missing a minus sign! You have listed "Latitude": 20.3484 and "Longitude": 57.5522. When I use minus for latitude (-20.3484) the location is indeed in Mauritius. However, that location is not at Middlesex University campus. Would you please @isubratty take a look at your location and submit a new PR to your data file with the correct exact coordinates!

**Comment by isubratty** [comment]
Hello Magnus,

I did the modification and sent a pull request.

Kind Regards,
Muhammad Irfaan Ali Subratty, MIET, MACM,
Young Professional Lead
IET CC-EMEA,
Chairperson
CyberCity ACM Chapter,
Committee Member
IET Mauritius,
Lead
IET Mauritius Young Professional Section,
IET Young Professional Ambassador,
Microsoft Learn Student Ambassador
________________________________

**Pull request merged**
