### PR TITLE
Add AZUG FR - Paris event

### PR DESCRIPTION
**Pull request by CedricLeblond**
Hello,

We are organizing a Global Azure event at Paris France and we could like to have our own community page and pin on the map !!

Thank you 😊

### CODE REVIEW

**Review by noopman — APPROVED** [review]
This looks great! @CedricLeblond @IhorLeontiev @zecloud @lecampusazure @CedricLeblond are you planning to publish your sessions on the site too using Sessionize?

**Comment by zecloud** [comment]
Hi @noopman 
yes the Sessionize should be activated soon it's here https://sessionize.com/global-azure-2023-france-globalazure/ 
Have a great day

**Comment by noopman** [comment]
That's great! You can add the SessionizeApiId alredy now to the data.json. Sessions will appear on the global azure site once you publish them from your event!

**Comment by zecloud** [comment]
It's all good so I've just created a new PR for the SessionizeApiId

**Pull request merged**
