### PR TITLE
Gabpoa - Brasil - RS

### PR DESCRIPTION
**Pull request by digomatos**

### CODE REVIEW

**Comment by tiagocostapt** [comment]
I just added some comments, please check. Happy to help if you need any assistance.

**Review by digomatos — COMMENTED** [review]
Ajustado index.md

**Review by digomatos — COMMENTED** [review]
Ajuste data.json

**Comment by tiagocostapt** [comment]
Can you update your site to reflect the 2025 event? https://gabpoa.azurewebsites.net still has information about 2024 event.

**Comment by digomatos** [comment]
> Can you update your site to reflect the 2025 event? https://gabpoa.azurewebsites.net still has information about 2024 event.

Sorry! I've already adjusted it!

**Comment by tiagocostapt** [comment]
Perfect!

**Pull request merged**
