### PR TITLE
Upload Azure Poland community

### PR DESCRIPTION
**Pull request by RogalaPiotr**

### CODE REVIEW

**Comment by hugobarona** [comment]
Hi @RogalaPiotr . Welcome to the Global Azure 23. Are you planning to use Sessionize for CfS? If so, the sessionize event id in the data.json file is not valid. Can you double check the id and ensure you are able to use the URL below to get the list of sessions for your event?

https://sessionize.com/api/v2/<event-id>/view/Sessions

**Comment by RogalaPiotr** [comment]
Hi @hugobarona , We haven't Sessionize so in that case I can remove this property? I wasn't sure and I used an older ID from last year - sorry. for that :/

**Comment by hugobarona** [comment]
No worries @RogalaPiotr . That's perfectly fine. I will merge this PR then. Thank you very much and happy Friday!

**Comment by RogalaPiotr** [comment]
@hugobarona done

**Comment by tiagocostapt** [comment]
Now, all looks good. Will approve.

**Pull request merged**
