### PR TITLE
Create Azure Bootcamp Shanghai event

### PR DESCRIPTION
**Pull request by HaoHoo**
Create Global Azure Bootcamp 2024 Shanghai event.

### CODE REVIEW

**Comment by tiagocostapt** [comment]
Hi @HaoHoo,

Can you update your website? https://globalazurebootcamp.devpro.group it seems to to be working. 

Thanks!

**Comment by HaoHoo** [comment]
Hi Tiago,

Sorry~ Looks like the service container has some issues. Please let me fix it and then update you.

Hao Hu
________________________________

**Comment by tiagocostapt** [comment]
I'm still having issues accessing https://[globalazurebootcamp.devpro.group](https://globalazurebootcamp.devpro.group/)/
Can you please have a look? 

image

**Comment by HaoHoo** [comment]
@tiagocostapt Sorry for the delay. I modified the app service code and fixed the URL in the JSON. Just recovered from sick 😄

**Pull request merged**
