### PR TITLE
moroccomsfcommunity

### PR DESCRIPTION
**Pull request by HassanFad**

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hi @HassanFad! This PR looks good. Couple of small things though:

* The data.json file is supposed to point to your logo image file: which is moroccomsftcom.PNG.
* It is a pity if you don't link to your homepage or your Sessionize from the index.md file! Would you not like to do that?

**Review by HassanFad — COMMENTED** [review]
logo name (moroccomsftcom.png) added to data.json file

**Review by HassanFad — COMMENTED** [review]
link to CFP page added

**Comment by HassanFad** [comment]
done

**Comment by HassanFad** [comment]
pls approve the last updates

**Pull request closed without merging**
