### PR TITLE
CloudAzureOsijek

### PR DESCRIPTION
**Pull request by tlulic**

### CODE REVIEW

**Comment by davidjrh** [comment]
Hi @tlulic I believe your PR is accidentally trying to delete Norways' community logo. Can you check the PR?

https://github.com/globalazure/communities/pull/46/commits/7212f121016be330081f9ea5f4d7cc046007e827

**Comment by tlulic** [comment]
Hello,

Yes, definately, it is accidentally. Please ignore

I will use my logo, and leave Norway. I'm sorry about problem

best

--
Tomislav Lulić
Microsoft MCSA | MCE | MVP | MCT
Mobile: +385 91 304 99 11
E-mail: ***@***.******@***.***>
Twitter: @tlulic
Blog: tlulic.wordpress.com
***@***.***

**Comment by davidjrh** [comment]
Hi @tlulic, I belive I'm going to put your files in a separate PR, because I'm not really sure what is going to happen if we accept this PR :) Working on it

image

**Comment by davidjrh** [comment]
Hi again, I've made your changes on PR #62, so closing this one.

**Pull request closed without merging**
