### PR TITLE
MUG Bo Added

### PR DESCRIPTION
**Pull request by AnahiSU**

### CODE REVIEW

**Comment by hugobarona** [comment]
Hi @AnahiSU . Welcome to the Global Azure 23. I just made a comment about the Sessionize configuration. Let me know your thoughts, so we can then close this PR. Thanks

**Comment by AnahiSU** [comment]
> Hi @AnahiSU . Welcome to the Global Azure 23. I just made a comment about the Sessionize configuration. Let me know your thoughts, so we can then close this PR. Thanks

Thank you, I think I fixed it.

**Comment by hugobarona** [comment]
Hi AnahiSU, thank you for your update. I noticed you did commit a vscode settings file. Can you please delete this file from your PR, so we can merge it?

image


Thanks.

**Comment by hugobarona** [comment]
Also, since you are using Sessionize, please collect your Sessionize API ID and provide it in the data.json file.
Note: I noticed your Sessionize event is in trial mode. You may need to modify it to avoid facing any issues once you start to do the Call for Speakers.
If you need help with that, please contact the Sessionize support team, and they will promptly reply back to you and give you instructions.

Thanks


https://sessionize.com/global-azure-mug-bolivia-2023/

**Comment by AnahiSU** [comment]
> Also, since you are using Sessionize, please collect your Sessionize API ID and provide it in the data.json file. Note: I noticed your Sessionize event is in trial mode. You may need to modify it to avoid facing any issues once you start to do the Call for Speakers. If you need help with that, please contact the Sessionize support team, and they will promptly reply back to you and give you instructions.
> 
> Thanks
> 
> https://sessionize.com/global-azure-mug-bolivia-2023/

Thank you and sorry for the issues and inconveniences. My team and I decided to not use sessionize because we are going to use only social media for this purposes. I think I fixed it this time.

**Comment by hugobarona** [comment]
> > Also, since you are using Sessionize, please collect your Sessionize API ID and provide it in the data.json file. Note: I noticed your Sessionize event is in trial mode. You may need to modify it to avoid facing any issues once you start to do the Call for Speakers. If you need help with that, please contact the Sessionize support team, and they will promptly reply back to you and give you instructions.
> > Thanks
> > https://sessionize.com/global-azure-mug-bolivia-2023/
> 
> Thank you and sorry for the issues and inconveniences. My team and I decided to not use sessionize because we are going to use only social media for this purposes. I think I fixed it this time.

That's perfectly fine @AnahiSU . Thank you very much for the updates. We are good to go. Have a great day!

**Pull request merged**
