### PR TITLE
Add Santiago de Chile as new City for 2024

### PR DESCRIPTION
**Pull request by wcalcagno**

### CODE REVIEW

**Comment by tiagocostapt** [comment]
@wcalcagno any feedback?

**Comment by tiagocostapt** [comment]
@wcalcagno, any update? Still interested in organizing an event?

**Comment by wcalcagno** [comment]
Yes we are interested

Please let me know another step we have to do.

Sorry for my bad English …

**Comment by tiagocostapt** [comment]
I have removed the file.

**Pull request merged**
