### PR TITLE
Gabpoa

### PR DESCRIPTION
**Pull request by digomatos**

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hi there! We need you to provide a community logo file (you indicated that it is called gabpoa.png but it is not present in your gabpoa folder), and also a .MD file presenting briefly your community! Please review all the information in our [ReadMe](https://github.com/globalazure/communities#readme) and amend your PR! Looking forward to having you at part of Global Azure 2023 with your Brazil community!

**Comment by noopman** [comment]
Please advise @digomatos!

**Comment by digomatos** [comment]
Adjusted, I apologize for being wrong

**Review by noopman — APPROVED** [review]
No problem, with the updates, all is now A-OK! Welcome to #GlobalAzure

**Pull request merged**
