### PR TITLE
added files to be submitted

### PR DESCRIPTION
**Pull request by MrKruge**
Azure Heroes Netherlands addition

### CODE REVIEW

**Comment by tiagocostapt** [comment]
Add some items for you review. If you need any assistance, please just let me know! Happy to help.

**Comment by MrKruge** [comment]
Sorry I’m not sure what you mean.  I added items for review I thought.
Thanks
Danny

**Comment by tiagocostapt** [comment]
You need to:

- Remove curly brackets on the lat/lon fields (line 27 of data.json)
- Add at least your GitHub handle in line 5 of data.json

**Comment by MrKruge** [comment]
hi, i have updated them :)

**Comment by tiagocostapt** [comment]
Awesome work!!!

**Comment by tiagocostapt** [comment]
🙏 Thank You for Your PR! 🎉

We really appreciate your contribution and the time you've been waiting. Your patience means a lot!

In the meantime, we have some exciting news… Global Azure as a brand-new website! 🎊🚀

Check out the new website, where you can register your event by filling out a simple form instead of submitting a PR. Find the BIG "Register an Event" button—you can’t miss it! 🟢📅 Let’s get those events rolling!

👉 [https://globalazure.net/](https://globalazure.net/)

Thanks again for your support, and happy event planning! 🎤🎟️🔥

**Comment by MrKruge** [comment]
Thank you for your response, I should have added it by the register event
now :) Thanks

**Pull request merged**
