### PR TITLE
Updated the index.json 

### PR DESCRIPTION
**Pull request by SARAN2991**

### CODE REVIEW

**Comment by SARAN2991** [comment]
Please approve the pull request , done some changes related to community details , venue and date .

**Comment by tiagocostapt** [comment]
Hi @SARAN2991, Global Azure is a global event from 18-20 April.
In this edit, you are changing the date to April 13th, 2024. Is this correct? This is out of our range of dates.

**Comment by tecnasau** [comment]
Good afternoon, support with the next branch, the data has been sent. https://github.com/globalazure/communities/compare/main...tecnasau:communities:patch-1

**Comment by SARAN2991** [comment]
Hi Tiago ,

yes i already discussed regarding it with Magnus Martensson  and the date
change is due to General elections in India during  the dates April 19 & 20
2024 , and followed by a very long weekend where all colleges and
workplaces will be on leave and all citizens will flew to their native
places to cast their votes , so only we have decided to prepone this event
on April 13th 2024 .

Regards,
Saravanan Ganesan.

**Comment by noopman** [comment]
Yes, this is all right @tiagocostapt. As discussed in email with @SARAN2991, they understand that sponsorships for these dates will be best effort from the GA side.

**Pull request merged**
