### PR TITLE
/2023/JOSCommunity

### PR DESCRIPTION
**Pull request by pnet2log**
A local community within Nigeria as part of the global azure communities event host.

### CODE REVIEW

**Comment by hugobarona** [comment]
Hi @pnet2log . Welcome to the Global Azure 23. Can you please add the index.md file to provide more details about your community and the logo file of your community as well, in case you have it. Also, on the data.json file, if you are not planning to use Sessionize, can you please keep the fields _SessionizeApiId_ and _SessionizeEventName_ empty.

Here is an example that you can rely to, so you understand what is missing.

https://github.com/globalazure/communities/tree/main/2023/azugpt

Thank you.

**Comment by pnet2log** [comment]
Thank you @hugobarona for the alert and yes @tiagocostapt will try my best to. Regards.   Working on it now.

**Comment by pnet2log** [comment]
Thank you @hugobarona for the alert and yes @tiagocostapt will try my best to. Regards.

**Comment by noopman** [comment]
Closing this due to inactivity!

**Pull request closed without merging**
