### PR TITLE
MCTNAIJA-TechUSERGROUP

### PR DESCRIPTION
**Pull request by OluwaseyiO**

### CODE REVIEW

**Review by noopman — CHANGES_REQUESTED** [review]
Hello there! This submission is not following the requested format for adding a community to Global Azure! You are supposed to create your own subfolder under the 2023 folder, with three files, and modify it to fit your community. Your community logo file, your community description in the .md file, and your community data in the .json file. If you need help, don't hesitate to ask! The idea is to follow the instructions in the [README](https://github.com/globalazure/communities#readme) section!

**Comment by OluwaseyiO** [comment]
Please Help ...
________________________________

**Comment by OluwaseyiO** [comment]
I have updated the files .  can check when i will be listed

**Comment by noopman** [comment]
> I have updated the files . can check when i will be listed

I am so sorry, @OluwaseyiO , but your Pull Request is in error! You have to make a new folder for your User Group under the folder 2023. Please look in that folder to see all the other User Groups who have done this before you! Copy what they have done in your code!

You must also undo the changes you have made to the _template/data.json file and also move your logo file into your subfolder!

For example your folder could be: 2023/TechUSERGROUP! It can then contain your version of the three files data.json, logo.png and and index.md!

Please make these changes, and I will review for you!

**Comment by OluwaseyiO** [comment]
Hello Magnus,

I have created a new folder , kindly help to review

https://github.com/ConvenantTechnologies/MCTNAIJA-TechUSERGROUP/tree/main/2023
[https://opengraph.githubassets.com/5ecd3c5282376069a61b8dc74927e984dc7902f554150a5b1d60a5e07f59598b/ConvenantTechnologies/MCTNAIJA-TechUSERGROUP]<https://github.com/ConvenantTechnologies/MCTNAIJA-TechUSERGROUP/tree/main/2023>
MCTNAIJA-TechUSERGROUP/2023 at main · ConvenantTechnologies/MCTNAIJA-TechUSERGROUP<https://github.com/ConvenantTechnologies/MCTNAIJA-TechUSERGROUP/tree/main/2023>
This is a repository for Global (Azure) Communities to maintain their page on the globalazure.net website. - MCTNAIJA-TechUSERGROUP/2023 at main · ConvenantTechnologies/MCTNAIJA-TechUSERGROUP
github.com

________________________________

**Review by noopman — CHANGES_REQUESTED** [review]
I am sorry @OluwaseyiO but there are still errors in this submission. Your NEW files MUST be located in  a SUBFOLDER of the folder 2023! Please refer to the readme.md of this repository for instructions! Also DO take a look at all the other community folders under the folder 2023 and create something similar for your community!

**Comment by OluwaseyiO** [comment]
Dear Magnus ,

This is done . Kindly review
________________________________

**Comment by noopman** [comment]
I fixed this for you @OluwaseyiO! Please verify your information on [https://globalazure.net/communities/2023](https://globalazure.net/communities/2023)!

**Pull request closed without merging**
