### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by srronaksingh**
Updated community link and Sessionize event title.

### CODE REVIEW

**Comment by tiagocostapt** [comment]
@srronaksingh please check the review I have opened on the data.json file.

**Review by srronaksingh — COMMENTED** [review]
i want to change the URL and Sessionize Event Name in this commit.

**Comment by tiagocostapt** [comment]
@srronaksingh , ok, but the URL you have changed to doesn't take it to the event website.

**Comment by srronaksingh** [comment]
just reverted the last commit.

**Comment by srronaksingh** [comment]
Community Link Updates and Location Coordinates.

**Comment by srronaksingh** [comment]
Community Link Updates and Location Coordinates.

**Comment by srronaksingh** [comment]
> @srronaksingh , ok, but the URL you have changed to doesn't take it to the event website.

Community Link Updates and Location Coordinates.

**Review by srronaksingh — COMMENTED** [review]
Community link and event location coordinates updates.

**Pull request merged**
